In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/netflix_titles_nov_2019.csv")
df

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
0,81193313,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
4,80213643,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show
...,...,...,...,...,...,...,...,...,...,...,...,...
5832,70141644,Mad Ron's Prevues from Hell,Jim Monaco,"Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...",United States,"November 1, 2010",1987,NR,84 min,"Cult Movies, Horror Movies","This collection cherry-picks trailers, forgott...",Movie
5833,70127998,Splatter,Joe Dante,"Corey Feldman, Tony Todd, Tara Leigh, Erin Way...",United States,"November 18, 2009",2009,TV-14,29 min,Horror Movies,"After committing suicide, a washed-up rocker r...",Movie
5834,70084180,Just Another Love Story,Ole Bornedal,"Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...",Denmark,"May 5, 2009",2007,NR,104 min,"Dramas, International Movies",When he causes a car accident that leaves a yo...,Movie
5835,70157452,Dinner for Five,NaN,NaN,United States,"February 4, 2008",2007,TV-MA,1 Season,Stand-Up Comedy & Talk Shows,"In each episode, four celebrities join host Jo...",TV Show
5836,70053412,To and From New York,Sorin Dan Mihalcescu,"Barbara King, Shaana Diya, John Krisiukenas, Y...",United States,"January 1, 2008",2006,NR,81 min,"Dramas, Independent Movies, Thrillers","While covering a story in New York City, a Sea...",Movie

In [3]:
df.iloc[3]

show_id                                                  81082007
title                                                   Atlantics
director                                                Mati Diop
cast            Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...
country                                  France, Senegal, Belgium
date_added                                      November 29, 2019
release_year                                                 2019
rating                                                      TV-14
duration                                                  106 min
listed_in        Dramas, Independent Movies, International Movies
description     Arranged to marry a rich man, young Ada is cru...
type                                                        Movie
Name: 3, dtype: object

In [4]:
df.iloc[67:89]

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
67,70053833,Black Snake Moan,Craig Brewer,"Samuel L. Jackson, Christina Ricci, Justin Tim...",United States,"November 20, 2019",2007,R,116 min,"Dramas, Independent Movies","Lazarus finds Rae beaten and near death, and a...",Movie
68,70122722,Carriers,"Àlex Pastor, David Pastor","Lou Taylor Pucci, Chris Pine, Piper Perabo, Em...",United States,"November 20, 2019",2009,PG-13,85 min,"Horror Movies, Sci-Fi & Fantasy, Thrillers","As a lethal virus spreads globally, four frien...",Movie
69,81217738,Dorasaani,KVR Mahendra,"Anand Deverakonda, Shivatmika Rajasekhar, Kann...",India,"November 20, 2019",2019,TV-14,134 min,"Dramas, International Movies, Romantic Movies",A village landlord's daughter and an educated ...,Movie
70,80081990,Dream/Killer,Andrew Jenks,"Bill Ferguson, Ryan Ferguson",United States,"November 20, 2019",2015,TV-MA,109 min,Documentaries,This riveting crime doc follows Bill as he con...,Movie
71,60004471,Evolution,Ivan Reitman,"David Duchovny, Julianne Moore, Orlando Jones,...",United States,"November 20, 2019",2001,PG-13,102 min,"Comedies, Sci-Fi & Fantasy",After two community college geology professors...,Movie
72,60022413,Eye for an Eye,John Schlesinger,"Sally Field, Kiefer Sutherland, Ed Harris, Bev...",United States,"November 20, 2019",1996,R,101 min,"Dramas, Thrillers",Grieving mother Karen McCann takes justice int...,Movie
73,81011957,Holiday Secrets,NaN,"Corinna Harfouch, Christiane Paul, Svenja Jung...",Germany,"November 20, 2019",2019,TV-MA,1 Season,"International TV Shows, TV Dramas",A Christmas reunion becomes a gateway to the p...,TV Show
74,70058022,Hot Rod,Akiva Schaffer,"Andy Samberg, Jorma Taccone, Bill Hader, Danny...",United States,"November 20, 2019",2007,PG-13,88 min,"Comedies, Sports Movies",Andy Samberg stars in this comedy as an accide...,Movie
75,60022502,It Takes Two,Andy Tennant,"Kirstie Alley, Steve Guttenberg, Mary-Kate Ols...",United States,"November 20, 2019",1995,PG,101 min,"Children & Family Movies, Comedies",The Olsen twins put a cute new spin on Mark Tw...,Movie
76,80244683,"Lorena, Light-Footed Woman",Juan Carlos Rulfo,Lorena Ramírez,Mexico,"November 20, 2019",2019,TV-G,28 min,"Documentaries, International Movies, Sports Mo...",Lorena Ramírez of Mexico's Rarámuri community ...,Movie
77,80028357,"Love, Rosie",Christian Ditter,"Lily Collins, Sam Claflin, Christian Cooke, Ja...","Germany, United Kingdom","November 20, 2019",2014,R,103 min,"Comedies, International Movies, Romantic Movies","Over the years, as they come and go in each ot...",Movie
78,81217739,Mallesham,Raj R,"Jhansi, Priyadarshi Pullikonda, Ananya Nagalla",India,"November 20, 2019",2019,TV-PG,131 min,"Dramas, Independent Movies, International Movies","A self-trained engineer risks debt, love and r...",Movie
79,60031884,Once Upon a Time in the West,Sergio Leone,"Henry Fonda, Charles Bronson, Claudia Cardinal...","Italy, United States","November 20, 2019",1968,PG-13,166 min,"Action & Adventure, Classic Movies, Internatio...","In this epic spaghetti Western, a flinty gunsl...",Movie
80,70117289,She's Out of My League,Jim Field Smith,"Jay Baruchel, Alice Eve, T.J. Miller, Mike Vog...",United States,"November 20, 2019",2010,R,105 min,"Comedies, Romantic Movies",When average-guy Kirk starts dating drop-dead-...,Movie
81,28631236,Superstar,Bruce McCulloch,"Molly Shannon, Will Ferrell, Elaine Hendrix, H...",United States,"November 20, 2019",1999,PG-13,82 min,Comedies,A socially awkward Catholic schoolgirl vows to...,Movie
82,70121502,The Adventures of Tintin,Steven Spielberg,"Jamie Bell, Andy Serkis, Daniel Craig, Nick Fr...","United States, New Zealand, United Kingdom","November 20, 2019",2011,PG,107 min,Children & Family Movies,This 3-D motion capture adapts Georges Remi's ...,Movie
83,70215455,The Devil Inside,William Brent Bell,"Fernanda Andrade, Simon Quarterman, Evan Helmu...",United States,"November 20, 2019",2012,R,84 min,"Horror Movies, Thrillers","At once spooky and grisly, this thriller follo...",Movie
84,506464,The First Wives Club,Hugh WIlson,"Bette Midler, Goldie Hawn, Diane Keaton, Maggi...",United States,"November 20, 2019",1996,PG,103 min,Comedies,Following a friend's suicide after her husband...,Movie
85,60003508,The Gift,Sam Raimi,"Cate Blanchett, Giovanni Ribisi, Keanu Reeves,...",United States,"November 20, 2019",2000,R,112 min,"Dramas, Thrillers",When the authorities find a drowned woman's bo...,Movie
86,70105132,"The Goods: Live Hard, Sell Hard",Neal Brennan,"Jeremy Piven, Ving Rhames, James Brolin, David...",United States,"November 20, 2019",2009,R,89 min,Comedies,Hired to rescue a flagging car dealership duri...,Movie
87,60004083,The Longest Yard,Robert Aldrich,"Burt Reynolds, Eddie Albert, Ed Lauter, James ...",United States,"November 20, 2019",1974,R,121 min,"Classic Movies, Comedies, Sports Movies",Washed-up professional quarterback Paul Crewe ...,Movie
88,70087538,The Love Guru,Marco Schnabel,"Mike Myers, Jessica Alba, Justin Timberlake, B...","United Kingdom, Germany, United States","November 20, 2019",2008,PG-13,87 min,"Comedies, Sports Movies","Raised on an ashram in India, a self-styled lo...",Movie

In [11]:
df.iloc[65:83:3]

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
65,70003046,Bebe's Kids,Bruce W. Smith,"Faizon Love, Vanessa Bell Calloway, Wayne Coll...",United States,"November 20, 2019",1992,PG-13,73 min,Comedies,"When ladies' man Robin meets Jamika, he falls ...",Movie
68,70122722,Carriers,"Àlex Pastor, David Pastor","Lou Taylor Pucci, Chris Pine, Piper Perabo, Em...",United States,"November 20, 2019",2009,PG-13,85 min,"Horror Movies, Sci-Fi & Fantasy, Thrillers","As a lethal virus spreads globally, four frien...",Movie
71,60004471,Evolution,Ivan Reitman,"David Duchovny, Julianne Moore, Orlando Jones,...",United States,"November 20, 2019",2001,PG-13,102 min,"Comedies, Sci-Fi & Fantasy",After two community college geology professors...,Movie
74,70058022,Hot Rod,Akiva Schaffer,"Andy Samberg, Jorma Taccone, Bill Hader, Danny...",United States,"November 20, 2019",2007,PG-13,88 min,"Comedies, Sports Movies",Andy Samberg stars in this comedy as an accide...,Movie
77,80028357,"Love, Rosie",Christian Ditter,"Lily Collins, Sam Claflin, Christian Cooke, Ja...","Germany, United Kingdom","November 20, 2019",2014,R,103 min,"Comedies, International Movies, Romantic Movies","Over the years, as they come and go in each ot...",Movie
80,70117289,She's Out of My League,Jim Field Smith,"Jay Baruchel, Alice Eve, T.J. Miller, Mike Vog...",United States,"November 20, 2019",2010,R,105 min,"Comedies, Romantic Movies",When average-guy Kirk starts dating drop-dead-...,Movie

In [12]:
df.iloc[567:789:5]

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
567,81132439,Travel Mates 2,Bedran Güzel,"Oğuzhan Koç, İbrahim Büyükak, Ezgi Eyüboğlu, O...",Turkey,"September 20, 2019",2018,TV-14,111 min,"Comedies, International Movies",When struggling singer Onur decides to return ...,Movie
572,70281312,The Blacklist,NaN,"James Spader, Megan Boone, Diego Klattenhoff, ...",United States,NaN,2019,TV-14,6 Seasons,"Crime TV Shows, TV Dramas, TV Thrillers","After turning himself in, a brilliant fugitive...",TV Show
577,80991316,Avengement,Jesse V. Johnson,"Scott Adkins, Craig Fairbrass, Thomas Turgoose...",United Kingdom,"September 17, 2019",2019,TV-MA,88 min,Action & Adventure,"Betrayed by his loan shark brother, a hardened...",Movie
582,80058248,I Am Wrath,Chuck Russell,"John Travolta, Christopher Meloni, Amanda Schu...",United States,"September 16, 2019",2016,R,91 min,"Action & Adventure, Dramas","Hell-bent on avenging his wife's murder, Stanl...",Movie
587,70143865,Pawn Stars,NaN,"Corey Harrison, Richard Harrison, Rick Harriso...",United States,"September 15, 2019",2010,TV-PG,1 Season,Reality TV,"Father Richard Harrison, son Rick and grandson...",TV Show
592,81176196,The Rap Game,NaN,Jermaine Dupri,United States,"September 15, 2019",2016,TV-14,1 Season,Reality TV,Young lyricists between the ages of 12 and 16 ...,TV Show
597,81092328,American Warfighter,Jerry G. Angelo,"Jerry G. Angelo, Paul Logan, Joshua Santana, C...",United States,"September 13, 2019",2019,TV-MA,106 min,Dramas,A Navy SEAL haunted by wartime memories tries ...,Movie
602,81095103,Kabaneri of the Iron Fortress: The Battle of U...,NaN,"Tasuku Hatanaka, Sayaka Senbongi, Maaya Uchida...",NaN,"September 13, 2019",2019,TV-MA,1 Season,"Anime Series, International TV Shows, TV Horror",Ikoma and the Iron Fortress take their fight t...,TV Show
607,81002412,Tall Girl,Nzingha Stewart,"Ava Michelle, Griffin Gluck, Sabrina Carpenter...",United States,"September 13, 2019",2019,TV-PG,103 min,"Children & Family Movies, Comedies, Romantic M...","After years of slouching through life, 6-foot-...",Movie
612,80153467,Unbelievable,NaN,"Toni Collette, Merritt Wever, Kaitlyn Dever, D...",United States,"September 13, 2019",2019,TV-MA,1 Season,"Crime TV Shows, TV Dramas",After a young woman is accused of lying about ...,TV Show
617,81060174,Bill Burr: Paper Tiger,Mike Binder,Bill Burr,"United States, United Kingdom","September 10, 2019",2019,TV-MA,67 min,Stand-Up Comedy,"Bill Burr unloads on outrage culture, male fem...",Movie
622,70302573,Sword Art Online,NaN,"Yoshitsugu Matsuoka, Haruka Tomatsu, Ayana Tak...",Japan,NaN,2014,TV-14,2 Seasons,"Anime Series, International TV Shows",A video game whiz helps create a new technolog...,TV Show
627,81113928,Care of Kancharapalem,Maha Venkatesh,"Subba Rao Vepada, Radha Bessy, Kesava Karri, N...",NaN,"September 6, 2019",2018,TV-14,142 min,"Comedies, Dramas, Independent Movies",From a schoolboy’s crush to a middle-aged bach...,Movie
632,81132437,Kill Me If You Dare,Şenol Sönmez,"Murat Boz, Seda Bakan, Açelya Topaloğlu, Özgür...",NaN,"September 6, 2019",2019,TV-14,100 min,"Comedies, International Movies, Romantic Movies","Bogged down with money problems, a couple grow...",Movie
637,81078908,The World We Make,Brian Baugh,"Caleb Castille, Rose Reid, Kevin Sizemore, Gre...",United States,"September 4, 2019",2019,PG,108 min,"Dramas, Romantic Movies",A teenage equestrian and a local football play...,Movie
642,81137484,Elena,Petra Costa,NaN,"Brazil, United States","September 1, 2019",2012,TV-14,81 min,"Documentaries, International Movies","In this documentary, the director remembers a ...",Movie
647,81073764,Loo Loo Kids: Johny & Friends Musical Adventures,NaN,NaN,NaN,"September 1, 2019",2016,TV-Y,1 Season,Kids' TV,Music-loving baby Johny goes on dance-filled a...,TV Show
652,70113003,My Sister's Keeper,Nick Cassavetes,"Cameron Diaz, Abigail Breslin, Alec Baldwin, J...",United States,"September 1, 2019",2009,PG-13,109 min,Dramas,A former defense attorney finds herself back i...,Movie
657,81137482,Olmo & the Seagull,"Petra Costa, Lea Glob","Olivia Corsini, Sergio Nicolai, Arman Saribeky...","Denmark, Brazil, France, Portugal, Sweden","September 1, 2019",2014,TV-MA,82 min,"Dramas, Independent Movies, International Movies",A pregnancy forces an actress out of her lates...,Movie
662,80053653,Scream,NaN,"Willa Fitzgerald, Bex Taylor-Klaus, John Karna...",United States,NaN,2019,TV-14,3 Seasons,"Crime TV Shows, TV Horror, TV Mysteries",In this new TV series sequel to the classic ho...,TV Show
667,81165786,The Bridge,Kunle Afolayan,"Chidinma Ekile, Ademola Adedoyin, Kunle Afolay...",Nigeria,"September 1, 2019",2017,TV-14,119 min,"Dramas, International Movies, Romantic Movies",A Yoruba prince and a young lady from a promin...,Movie
672,70112730,The Taking of Pelham 123,Tony Scott,"Denzel Washington, John Travolta, Luis Guzmán,...","United States, United Kingdom","September 1, 2019",2009,R,106 min,Action & Adventure,When a group of hijackers takes passengers abo...,Movie
677,81065786,Used Goods,Mohamed Hamdy,"Mohamed Ragab, Ayten Amer, Hassan Abdulfattah",Egypt,"September 1, 2019",2018,TV-MA,95 min,"Action & Adventure, Comedies, International Mo...","To evade greedy pharmaceutical crooks, a medic...",Movie
682,81091381,Feo pero sabroso,Fernando Ayllón,"Iván Marín, Lina Cardona, Carlos Barbosa, Ana ...",Colombia,"August 30, 2019",2018,TV-MA,91 min,"Comedies, International Movies",When an unattractive man gets engaged to a bea...,Movie
687,80148535,The Dark Crystal: Age of Resistance,NaN,"Taron Egerton, Nathalie Emmanuel, Anya Taylor-...","United Kingdom, United States","August 30, 2019",2019,TV-PG,1 Season,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",As power-hungry overlords drain life from the ...,TV Show
692,81167494,Expo,Joseph Mbah,"Derek Davenport, Amelia Haberman, Shepsut Wils...",United States,"August 29, 2019",2019,TV-14,81 min,"Action & Adventure, Dramas, Independent Movies","Mistakenly accused of kidnapping, a veteran so...",Movie
697,81029611,Droppin' Cash: Los Angeles,NaN,NaN,United States,NaN,2019,TV-MA,2 Seasons,Reality TV,This Complex series follows the paper trail of...,TV Show
702,81140577,Dave Chappelle: Sticks & Stones,Stan Lathan,Dave Chappelle,United States,"August 26, 2019",2019,TV-MA,66 min,Stand-Up Comedy,"Dave Chappelle takes on gun culture, the opioi...",Movie
707,80996791,13 Reasons Why: Beyond the Reasons,NaN,"Dylan Minnette, Katherine Langford, Kate Walsh...",United States,NaN,2019,TV-MA,3 Seasons,"Crime TV Shows, Docuseries","Cast members, writers, producers and mental he...",TV Show
712,80203254,Rust Valley Restorers,NaN,"Mike Hall, Michael Daingerfield",Canada,"August 23, 2019",2019,TV-14,1 Season,"International TV Shows, Reality TV","Old-school auto collector Mike Hall, his pal A...",TV Show
717,81151880,Game Over (Hindi Version),Ashwin Saravanan,"Taapsee Pannu, Vinodhini, Parvathi T, Ramya Su...","India, Turkey","August 21, 2019",2019,TV-MA,98 min,"Horror Movies, International Movies, Thrillers","As a series of murders hit close to home, a vi...",Movie
722,60021787,Gangs of New York,Martin Scorsese,"Leonardo DiCaprio, Daniel Day-Lewis, Cameron D...","United States, Italy","August 20, 2019",2002,R,167 min,Dramas,In the crime-ridden slums of New York in the 1...,Movie
727,81026915,Better Than Us,NaN,"Paulina Andreeva, Kirill Käro, Aleksandr Ustyu...",Russia,"August 16, 2019",2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A family on the brink of splitting up become t...,TV Show
732,70204989,Gunslinger Girl,NaN,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,NaN,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","On the surface, the Social Welfare Agency appe...",TV Show
737,80231419,Sextuplets,Michael Tiddes,"Marlon Wayans, Bresha Webb, Michael Ian Black,...",United States,"August 16, 2019",2019,TV-14,100 min,Comedies,When a dad-to-be learns he's actually a sextup...,Movie
742,80195357,Cannon Busters,NaN,"Yoshitsugu Matsuoka, Hinaki Yano, Shiori Izawa...","United States, Japan","August 15, 2019",2019,TV-MA,1 Season,"Anime Series, International TV Shows",Immortal renegade Philly the Kid and his trans...,TV Show
747,80223113,Happy Jail,NaN,NaN,NaN,"August 14, 2019",2019,TV-MA,1 Season,"Crime TV Shows, Docuseries",The Philippine jail known for a viral Michael ...,TV Show
752,81123826,Hasta los dientes,Alberto Arnaut Estrada,NaN,Mexico,"August 13, 2019",2018,TV-MA,109 min,"Documentaries, International Movies",This documentary follows the controversy surro...,Movie
757,80100929,Cable Girls,NaN,"Blanca Suárez, Nadia de Santiago, Ana Fernánde...",Spain,NaN,2019,TV-MA,4 Seasons,"International TV Shows, Romantic TV Shows, Spa...","In 1920s Madrid, four women at the National Te...",TV Show
762,81091977,Rocko's Modern Life: Static Cling,"Joe Murray, Cosmo Segurson","Carlos Alazraqui, Tom Kenny, Charlie Adler, Ji...",United States,"August 9, 2019",2019,TV-Y7,46 min,"Children & Family Movies, Comedies, LGBTQ Movies","After 20 years in space, Rocko struggles to ad...",Movie
767,81153372,Westside vs. the World,Michael Fahey,"Ron Perlman, Louie Simmons",NaN,"August 9, 2019",2019,TV-MA,96 min,"Documentaries, Sports Movies",A look into the journey of influential strengt...,Movie
772,80183878,Let's Eat 2,NaN,"Yoon Du-jun, Seo Hyun-jin, Kwon Yul, Kim Hee-w...","Malaysia, Singapore, Hong Kong","August 8, 2019",2015,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Two classmates from elementary school reunite ...,TV Show
777,70297144,Reply 1997,Shin Won-ho,"Jung Eun-ji, Seo In-guk, Shin So-yul, Ji-won E...",South Korea,"August 8, 2019",2012,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...","As a teen, Shi Won was obsessed with a boy ban...",TV Show
782,81112446,Badla,Sujoy Ghosh,"Amitabh Bachchan, Taapsee Pannu, Amrita Singh,...",India,"August 7, 2019",2019,TV-14,117 min,"International Movies, Thrillers","When a woman is accused of killing her lover, ...",Movie
787,80002621,Jim Jefferies : BARE,Shannon Hartman,Jim Jefferies,United States,"August 6, 2019",2014,NR,77 min,Stand-Up Comedy,Nothing is sacred in this show from Australian...,Movie

In [13]:
df.iloc[:,1:5]

,title,director,cast,country
0,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea
1,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN
2,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India
3,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium"
4,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom"
...,...,...,...,...
5832,Mad Ron's Prevues from Hell,Jim Monaco,"Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...",United States
5833,Splatter,Joe Dante,"Corey Feldman, Tony Todd, Tara Leigh, Erin Way...",United States
5834,Just Another Love Story,Ole Bornedal,"Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...",Denmark
5835,Dinner for Five,NaN,NaN,United States
5836,To and From New York,Sorin Dan Mihalcescu,"Barbara King, Shaana Diya, John Krisiukenas, Y...",United States

In [14]:
df.iloc[45:100,::-1]

,type,description,listed_in,duration,rating,release_year,date_added,country,cast,director,title,show_id
45,Movie,Thrust from a violent home into a brutal custo...,"Dramas, Independent Movies, International Movies",97 min,TV-MA,2019,"November 22, 2019",France,"MHD, Darren Muselet, Aïssa Maïga, Jalil Lesper...",Julien Abraham,Brother,80198859
46,TV Show,"When she gets angry, middle schooler Naoko tur...","Anime Series, Kids' TV",1 Season,TV-Y7-FV,2019,"November 22, 2019","United States, Japan","Naoko Matsui, Hiroshi Kamiya, Kazue Ikura, Cha...",NaN,Dino Girl Gauko,80216180
47,TV Show,"Eight stories celebrating family, faith, love ...",TV Dramas,1 Season,TV-14,2019,"November 22, 2019",United States,"Dolly Parton, Julianne Hough, Kimberly William...",NaN,Dolly Parton's Heartstrings,80244846
48,Movie,The girls of Ōarai High must face off against ...,"Action & Adventure, Anime Features, Internatio...",121 min,TV-14,2015,"November 22, 2019",Japan,"Mai Fuchigami, Ai Kayano, Mami Ozaki, Ikumi Na...",Tsutomu Mizushima,Girls und Panzer der Film,80159876
49,TV Show,Two sisters discover disturbing family secrets...,"Crime TV Shows, International TV Shows, Spanis...",2 Seasons,TV-MA,2019,NaN,Spain,"Ivana Baquero, Jon Kortajarena, Alejandra Onie...",NaN,High Seas,80233258
50,Movie,Mike Birbiglia performs in this live concert s...,Stand-Up Comedy,56 min,TV-14,2008,"November 22, 2019",United States,Mike Birbiglia,NaN,Mike Birbiglia: What I Should Have Said Was No...,70091304
51,TV Show,"It's the ""Nailed It!"" holiday special you've b...",Reality TV,2 Seasons,TV-PG,2019,NaN,United States,"Nicole Byer, Jacques Torres",NaN,Nailed It! Holiday!,81019894
52,TV Show,Ride along as police officers and drug smuggle...,"Crime TV Shows, Docuseries",1 Season,TV-MA,2019,"November 22, 2019",United States,NaN,NaN,Narcoworld: Dope Stories,81169145
53,TV Show,"A new guardian ""angelus"" uncovers a secret beh...","International TV Shows, TV Comedies, TV Dramas",1 Season,TV-MA,2019,"November 22, 2019",Brazil,"Victor Lamoglia, Júlia Rabello, Kéfera Buchman...",NaN,Nobody's Looking,80244700
54,Movie,"Featuring interviews and vintage footage, this...","Documentaries, Sports Movies",119 min,TV-14,2019,"November 22, 2019",United States,Carroll Shelby,"Nate Adams, Adam Carolla",Shelby American,81218074
55,TV Show,Peer into the lives of young Singaporeans as t...,"International TV Shows, Reality TV",1 Season,TV-MA,2019,"November 22, 2019","Singapore, United States","Nicole Ong, Mae Tan, Sukki Singapora, Vinny Sh...",NaN,Singapore Social,80245262
56,TV Show,An extraordinary discovery inspires two human ...,"Kids' TV, TV Action & Adventure, TV Sci-Fi & F...",3 Seasons,TV-Y7-FV,2019,NaN,"United States, Canada","Jack De Sena, Paula Burrows, Sasha Rojen, Jaso...",NaN,The Dragon Prince,80212245
57,TV Show,As Queen Poppy welcomes a new time of peace in...,"Kids' TV, TV Comedies",8 Seasons,TV-G,2019,NaN,United States,"Amanda Leighton, Skylar Astin, Ron Funches, Da...",NaN,Trolls: The Beat Goes On!,80117560
58,Movie,On board Russia's first nuclear ballistic subm...,"Action & Adventure, Dramas",138 min,PG-13,2002,"November 21, 2019","United Kingdom, Germany, Canada, United States","Harrison Ford, Liam Neeson, Peter Sarsgaard, S...",Kathryn Bigelow,K-19: The Widowmaker,60023606
59,TV Show,After making a deal with a supernatural figure...,"Crime TV Shows, International TV Shows, TV Dramas",1 Season,TV-MA,2019,"November 21, 2019",France,"Carl Malapa, Nemo Schiffman, Manon Bresch, Cor...",NaN,Mortel,80241539
60,Movie,Medieval magic sends a 14th-century knight to ...,"Children & Family Movies, Comedies, Romantic M...",93 min,TV-14,2019,"November 21, 2019",United States,"Vanessa Hudgens, Josh Whitehouse, Emmanuelle C...",Monika Mitchell,The Knight Before Christmas,81026188
61,Movie,When lifelong friends Roz and Lil fall in love...,"Dramas, Independent Movies, International Movies",111 min,R,2013,"November 20, 2019","Australia, France","Naomi Watts, Robin Wright, Xavier Samuel, Jame...",Anne Fontaine,Adore,70267398
62,TV Show,"Living under the same roof, a group of unabash...","International TV Shows, TV Comedies, TV Dramas",1 Season,TV-14,2019,"November 20, 2019",NaN,"Vayu Kessuvit, Ekapol Deebunmee, Nuttapong Boo...",NaN,Bangkok Buddies,81152643
63,Movie,"To escape the stress of fame, teen pop star Jo...","Comedies, Dramas, Romantic Movies",88 min,PG,2016,"November 20, 2019",United States,"Matthew Espinosa, Sarah Jeffery, Allison Paige...",Joshua Caldwell,Be Somebody,80108983
64,Movie,"After realizing that their boob tube is gone, ...","Comedies, Cult Movies",81 min,PG-13,1996,"November 20, 2019",United States,"Mike Judge, Bruce Willis, Demi Moore, Cloris L...",Mike Judge,Beavis and Butt-head Do America,292118
65,Movie,"When ladies' man Robin meets Jamika, he falls ...",Comedies,73 min,PG-13,1992,"November 20, 2019",United States,"Faizon Love, Vanessa Bell Calloway, Wayne Coll...",Bruce W. Smith,Bebe's Kids,70003046
66,Movie,This documentary charts the rise and fall of h...,Documentaries,86 min,TV-MA,2019,"November 20, 2019",United States,Bikram Choudhury,Eva Orner,"Bikram: Yogi, Guru, Predator",80221584
67,Movie,"Lazarus finds Rae beaten and near death, and a...","Dramas, Independent Movies",116 min,R,2007,"November 20, 2019",United States,"Samuel L. Jackson, Christina Ricci, Justin Tim...",Craig Brewer,Black Snake Moan,70053833
68,Movie,"As a lethal virus spreads globally, four frien...","Horror Movies, Sci-Fi & Fantasy, Thrillers",85 min,PG-13,2009,"November 20, 2019",United States,"Lou Taylor Pucci, Chris Pine, Piper Perabo, Em...","Àlex Pastor, David Pastor",Carriers,70122722
69,Movie,A village landlord's daughter and an educated ...,"Dramas, International Movies, Romantic Movies",134 min,TV-14,2019,"November 20, 2019",India,"Anand Deverakonda, Shivatmika Rajasekhar, Kann...",KVR Mahendra,Dorasaani,81217738
70,Movie,This riveting crime doc follows Bill as he con...,Documentaries,109 min,TV-MA,2015,"November 20, 2019",United States,"Bill Ferguson, Ryan Ferguson",Andrew Jenks,Dream/Killer,80081990
71,Movie,After two community college geology professors...,"Comedies, Sci-Fi & Fantasy",102 min,PG-13,2001,"November 20, 2019",United States,"David Duchovny, Julianne Moore, Orlando Jones,...",Ivan Reitman,Evolution,60004471
72,Movie,Grieving mother Karen McCann takes justice int...,"Dramas, Thrillers",101 min,R,1996,"November 20, 2019",United States,"Sally Field, Kiefer Sutherland, Ed Harris, Bev...",John Schlesinger,Eye for an Eye,60022413
73,TV Show,A Christmas reunion becomes a gateway to the p...,"International TV Shows, TV Dramas",1 Season,TV-MA,2019,"November 20, 2019",Germany,"Corinna Harfouch, Christiane Paul, Svenja Jung...",NaN,Holiday Secrets,81011957
74,Movie,Andy Samberg stars in this comedy as an accide...,"Comedies, Sports Movies",88 min,PG-13,2007,"November 20, 2019",United States,"Andy Samberg, Jorma Taccone, Bill Hader, Danny...",Akiva Schaffer,Hot Rod,70058022
75,Movie,The Olsen twins put a cute new spin on Mark Tw...,"Children & Family Movies, Comedies",101 min,PG,1995,"November 20, 2019",United States,"Kirstie Alley, Steve Guttenberg, Mary-Kate Ols...",Andy Tennant,It Takes Two,60022502
76,Movie,Lorena Ramírez of Mexico's Rarámuri community ...,"Documentaries, International Movies, Sports Mo...",28 min,TV-G,2019,"November 20, 2019",Mexico,Lorena Ramírez,Juan Carlos Rulfo,"Lorena, Light-Footed Woman",80244683
77,Movie,"Over the years, as they come and go in each ot...","Comedies, International Movies, Romantic Movies",103 min,R,2014,"November 20, 2019","Germany, United Kingdom","Lily Collins, Sam Claflin, Christian Cooke, Ja...",Christian Ditter,"Love, Rosie",80028357
78,Movie,"A self-trained engineer risks debt, love and r...","Dramas, Independent Movies, International Movies",131 min,TV-PG,2019,"November 20, 2019",India,"Jhansi, Priyadarshi Pullikonda, Ananya Nagalla",Raj R,Mallesham,81217739
79,Movie,"In this epic spaghetti Western, a flinty gunsl...","Action & Adventure, Classic Movies, Internatio...",166 min,PG-13,1968,"November 20, 2019","Italy, United States","Henry Fonda, Charles Bronson, Claudia Cardinal...",Sergio Leone,Once Upon a Time in the West,60031884
80,Movie,When average-guy Kirk starts dating drop-dead-...,"Comedies, Romantic Movies",105 min,R,2010,"November 20, 2019",United States,"Jay Baruchel, Alice Eve, T.J. Miller, Mike Vog...",Jim Field Smith,She's Out of My League,70117289
81,Movie,A socially awkward Catholic schoolgirl vows to...,Comedies,82 min,PG-13,1999,"November 20, 2019",United States,"Molly Shannon, Will Ferrell, Elaine Hendrix, H...",Bruce McCulloch,Superstar,28631236
82,Movie,This 3-D motion capture adapts Georges Remi's ...,Children & Family Movies,107 min,PG,2011,"November 20, 2019","United States, New Zealand, United Kingdom","Jamie Bell, Andy Serkis, Daniel Craig, Nick Fr...",Steven Spielberg,The Adventures of Tintin,70121502
83,Movie,"At once spooky and grisly, this thriller follo...","Horror Movies, Thrillers",84 min,R,2012,"November 20, 2019",United States,"Fernanda Andrade, Simon Quarterman, Evan Helmu...",William Brent Bell,The Devil Inside,70215455
84,Movie,Following a friend's suicide after her husband...,Comedies,103 min,PG,1996,"November 20, 2019",United States,"Bette Midler, Goldie Hawn, Diane Keaton, Maggi...",Hugh WIlson,The First Wives Club,506464
85,Movie,When the authorities find a drowned woman's bo...,"Dramas, Thrillers",112 min,R,2000,"November 20, 2019",United States,"Cate Blanchett, Giovanni Ribisi, Keanu Reeves,...",Sam Raimi,The Gift,60003508
86,Movie,Hired to rescue a flagging car dealership duri...,Comedies,89 min,R,2009,"November 20, 2019",United States,"Jeremy Piven, Ving Rhames, James Brolin, David...",Neal Brennan,"The Goods: Live Hard, Sell Hard",70105132
87,Movie,Washed-up professional quarterback Paul Crewe ...,"Classic Movies, Comedies, Sports Movies",121 min,R,1974,"November 20, 2019",United States,"Burt Reynolds, Eddie Albert, Ed Lauter, James ...",Robert Aldrich,The Longest Yard,60004083
88,Movie,"Raised on an ashram in India, a self-styled lo...","Comedies, Sports Movies",87 min,PG-13,2008,"November 20, 2019","United Kingdom, Germany, United States","Mike Myers, Jessica Alba, Justin Timberlake, B...",Marco Schnabel,The Love Guru,70087538
89,Movie,A young attorney and a scrappy paralegal work ...,"Dramas, Thrillers",136 min,PG-13,1997,"November 20, 2019","United States, Germany","Matt Damon, Danny DeVito, Claire Danes, Jon Vo...",Francis Ford Coppola,The Rainmaker,1181661
90,Movie,"In a backwater Iowa town, young Gilbert is tor...","Classic Movies, Dramas, Independent Movies",118 min,PG-13,1993,"November 20, 2019",United States,"Johnny Depp, Leonardo DiCaprio, Juliette Lewis...",Lasse Hallström,What's Eating Gilbert Grape,60011552
91,TV Show,"When their 4-year-old son is murdered, a young...","Crime TV Shows, Docuseries, International TV S...",1 Season,TV-MA,2019,"November 20, 2019",France,NaN,NaN,Who Killed Little Gregory?,80222157
92,Movie,"Working under treacherous conditions, an army ...","Action & Adventure, Dramas",129 min,PG-13,2006,"November 20, 2019",United States,"Nicolas Cage, Michael Peña, Maggie Gyllenhaal,...",Oliver Stone,World Trade Center,70044693
93,Movie,When a divorced writer gets a letter from an o...,"Comedies, Dramas, Independent Movies",94 min,R,2011,"November 20, 2019",United States,"Charlize Theron, Patton Oswalt, Patrick Wilson...",Jason Reitman,Young Adult,70173046
94,Movie,When a father of eight and a mother of 10 prep...,"Children & Family Movies, Comedies",88 min,PG,2005,"November 20, 2019",United States,"Dennis Quaid, Rene Russo, Sean Faris, Katija P...",Raja Gosnell,"Yours, Mine and Ours",70039187
95,Movie,"A political cartoonist, a crime reporter and a...","Cult Movies, Dramas, Thrillers",158 min,R,2007,"November 20, 2019",United States,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",David Fincher,Zodiac,70044686
96,Movie,"Here comes the bride, and she's got plenty to ...",Stand-Up Comedy,78 min,TV-MA,2019,"November 19, 2019",United States,Iliza Shlesinger,Steve Paley,Iliza Shlesinger: Unveiled,81073633
97,TV Show,After ditching her domestic life to become a c...,"International TV Shows, Romantic TV Shows, TV ...",1 Season,TV-14,2019,"November 19, 2019",NaN,"Wanida Termthanaporn, Jason Young, Thanawin Te...",NaN,Miss Culinary,81152642
98,TV Show,"Follow Santiago Artemis, a Buenos Aires fashio...","International TV Shows, Reality TV, Spanish-La...",1 Season,TV-MA,2019,"November 19, 2019",Argentina,Santiago Artemis,NaN,No Time for Shame,81105522
99,TV Show,"When a wardrobe malfunction goes viral, a bubb...","International TV Shows, TV Dramas, Teen TV Shows",1 Season,TV-MA,2019,"November 17, 2019",Taiwan,"Ruby Zhan, Suun Lin, Sunnie Wang, Dean Tang, L...",NaN,Candy Online,81191473

In [16]:
df.iloc[[7,45,66,78,86,88,99,103],[5,8,11,10]]

,date_added,duration,type,description
7,"November 29, 2019",107 min,Movie,The life and times of iconic South African lib...
45,"November 22, 2019",97 min,Movie,Thrust from a violent home into a brutal custo...
66,"November 20, 2019",86 min,Movie,This documentary charts the rise and fall of h...
78,"November 20, 2019",131 min,Movie,"A self-trained engineer risks debt, love and r..."
86,"November 20, 2019",89 min,Movie,Hired to rescue a flagging car dealership duri...
88,"November 20, 2019",87 min,Movie,"Raised on an ashram in India, a self-styled lo..."
99,"November 17, 2019",1 Season,TV Show,"When a wardrobe malfunction goes viral, a bubb..."
103,"November 16, 2019",84 min,Movie,America's most beloved ventriloquist hits the ...

In [17]:
df.columns

Index(['show_id', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'type'],
      dtype='object')

In [19]:
df.set_index("title")

,show_id,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
title,,,,,,,,,,,
Chocolate,81193313,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
Guatemala: Heart of the Mayan World,81197050,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
The Zoya Factor,81213894,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
Atlantics,81082007,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
Chip and Potato,80213643,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show
...,...,...,...,...,...,...,...,...,...,...,...
Mad Ron's Prevues from Hell,70141644,Jim Monaco,"Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...",United States,"November 1, 2010",1987,NR,84 min,"Cult Movies, Horror Movies","This collection cherry-picks trailers, forgott...",Movie
Splatter,70127998,Joe Dante,"Corey Feldman, Tony Todd, Tara Leigh, Erin Way...",United States,"November 18, 2009",2009,TV-14,29 min,Horror Movies,"After committing suicide, a washed-up rocker r...",Movie
Just Another Love Story,70084180,Ole Bornedal,"Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...",Denmark,"May 5, 2009",2007,NR,104 min,"Dramas, International Movies",When he causes a car accident that leaves a yo...,Movie
Dinner for Five,70157452,NaN,NaN,United States,"February 4, 2008",2007,TV-MA,1 Season,Stand-Up Comedy & Talk Shows,"In each episode, four celebrities join host Jo...",TV Show
To and From New York,70053412,Sorin Dan Mihalcescu,"Barbara King, Shaana Diya, John Krisiukenas, Y...",United States,"January 1, 2008",2006,NR,81 min,"Dramas, Independent Movies, Thrillers","While covering a story in New York City, a Sea...",Movie

In [20]:
df

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
0,81193313,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
4,80213643,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show
...,...,...,...,...,...,...,...,...,...,...,...,...
5832,70141644,Mad Ron's Prevues from Hell,Jim Monaco,"Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...",United States,"November 1, 2010",1987,NR,84 min,"Cult Movies, Horror Movies","This collection cherry-picks trailers, forgott...",Movie
5833,70127998,Splatter,Joe Dante,"Corey Feldman, Tony Todd, Tara Leigh, Erin Way...",United States,"November 18, 2009",2009,TV-14,29 min,Horror Movies,"After committing suicide, a washed-up rocker r...",Movie
5834,70084180,Just Another Love Story,Ole Bornedal,"Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...",Denmark,"May 5, 2009",2007,NR,104 min,"Dramas, International Movies",When he causes a car accident that leaves a yo...,Movie
5835,70157452,Dinner for Five,NaN,NaN,United States,"February 4, 2008",2007,TV-MA,1 Season,Stand-Up Comedy & Talk Shows,"In each episode, four celebrities join host Jo...",TV Show
5836,70053412,To and From New York,Sorin Dan Mihalcescu,"Barbara King, Shaana Diya, John Krisiukenas, Y...",United States,"January 1, 2008",2006,NR,81 min,"Dramas, Independent Movies, Thrillers","While covering a story in New York City, a Sea...",Movie

In [21]:
df.set_index("title",inplace=True)

In [22]:
df

,show_id,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
title,,,,,,,,,,,
Chocolate,81193313,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
Guatemala: Heart of the Mayan World,81197050,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
The Zoya Factor,81213894,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
Atlantics,81082007,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
Chip and Potato,80213643,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show
...,...,...,...,...,...,...,...,...,...,...,...
Mad Ron's Prevues from Hell,70141644,Jim Monaco,"Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...",United States,"November 1, 2010",1987,NR,84 min,"Cult Movies, Horror Movies","This collection cherry-picks trailers, forgott...",Movie
Splatter,70127998,Joe Dante,"Corey Feldman, Tony Todd, Tara Leigh, Erin Way...",United States,"November 18, 2009",2009,TV-14,29 min,Horror Movies,"After committing suicide, a washed-up rocker r...",Movie
Just Another Love Story,70084180,Ole Bornedal,"Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...",Denmark,"May 5, 2009",2007,NR,104 min,"Dramas, International Movies",When he causes a car accident that leaves a yo...,Movie
Dinner for Five,70157452,NaN,NaN,United States,"February 4, 2008",2007,TV-MA,1 Season,Stand-Up Comedy & Talk Shows,"In each episode, four celebrities join host Jo...",TV Show
To and From New York,70053412,Sorin Dan Mihalcescu,"Barbara King, Shaana Diya, John Krisiukenas, Y...",United States,"January 1, 2008",2006,NR,81 min,"Dramas, Independent Movies, Thrillers","While covering a story in New York City, a Sea...",Movie

In [30]:
df.loc[df.index[1], ["cast"]]
df.loc["To and From New York", ["cast"]]

cast    Barbara King, Shaana Diya, John Krisiukenas, Y...
Name: To and From New York, dtype: object

In [34]:
df.loc[df.index[3:90],["cast"]]

                                                                                     cast
title
Atlantics                               Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...
Chip and Potato                         Abigail Oliver, Andrea Libman, Briana Buckmast...
Crazy people                            Ramsey Nouah, Chigul, Sola Sobowale, Ireti Doy...
I Lost My Body                          Hakim Faris, Victoire Du Bois, Patrick d'Assum...
Kalushi: The Story of Solomon Mahlangu  Thabo Rametsi, Thabo Malema, Welile Nzuza, Jaf...
...                                                                                   ...
The Gift                                Cate Blanchett, Giovanni Ribisi, Keanu Reeves,...
The Goods: Live Hard, Sell Hard         Jeremy Piven, Ving Rhames, James Brolin, David...
The Longest Yard                        Burt Reynolds, Eddie Albert, Ed Lauter, James ...
The Love Guru                           Mike Myers, Jessica Alba, Justin Timberlake, B...
The Rainmaker                           Matt Damon, Danny DeVito, Claire Danes, Jon Vo...

[87 rows x 1 columns]

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5837 entries, Chocolate to To and From New York
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5837 non-null   int64
 1   director      3936 non-null   object
 2   cast          5281 non-null   object
 3   country       5410 non-null   object
 4   date_added    5195 non-null   object
 5   release_year  5837 non-null   int64
 6   rating        5827 non-null   object
 7   duration      5837 non-null   object
 8   listed_in     5837 non-null   object
 9   description   5837 non-null   object
 10  type          5837 non-null   object
dtypes: int64(2), object(9)
memory usage: 676.3+ KB

In [36]:
df.describe()

            show_id  release_year
count  5.837000e+03   5837.000000
mean   7.730079e+07   2013.688539
std    9.479777e+06      8.419088
min    2.698800e+05   1925.000000
25%    8.004520e+07   2013.000000
50%    8.016353e+07   2016.000000
75%    8.024188e+07   2018.000000
max    8.122720e+07   2020.000000

In [37]:
df

,show_id,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
title,,,,,,,,,,,
Chocolate,81193313,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
Guatemala: Heart of the Mayan World,81197050,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
The Zoya Factor,81213894,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
Atlantics,81082007,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
Chip and Potato,80213643,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show
...,...,...,...,...,...,...,...,...,...,...,...
Mad Ron's Prevues from Hell,70141644,Jim Monaco,"Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...",United States,"November 1, 2010",1987,NR,84 min,"Cult Movies, Horror Movies","This collection cherry-picks trailers, forgott...",Movie
Splatter,70127998,Joe Dante,"Corey Feldman, Tony Todd, Tara Leigh, Erin Way...",United States,"November 18, 2009",2009,TV-14,29 min,Horror Movies,"After committing suicide, a washed-up rocker r...",Movie
Just Another Love Story,70084180,Ole Bornedal,"Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...",Denmark,"May 5, 2009",2007,NR,104 min,"Dramas, International Movies",When he causes a car accident that leaves a yo...,Movie
Dinner for Five,70157452,NaN,NaN,United States,"February 4, 2008",2007,TV-MA,1 Season,Stand-Up Comedy & Talk Shows,"In each episode, four celebrities join host Jo...",TV Show
To and From New York,70053412,Sorin Dan Mihalcescu,"Barbara King, Shaana Diya, John Krisiukenas, Y...",United States,"January 1, 2008",2006,NR,81 min,"Dramas, Independent Movies, Thrillers","While covering a story in New York City, a Sea...",Movie

In [38]:
df,df.isnull()

(                                      show_id                    director  \
 title
 Chocolate                            81193313                         NaN
 Guatemala: Heart of the Mayan World  81197050  Luis Ara, Ignacio Jaunsolo
 The Zoya Factor                      81213894             Abhishek Sharma
 Atlantics                            81082007                   Mati Diop
 Chip and Potato                      80213643                         NaN
 ...                                       ...                         ...
 Mad Ron's Prevues from Hell          70141644                  Jim Monaco
 Splatter                             70127998                   Joe Dante
 Just Another Love Story              70084180                Ole Bornedal
 Dinner for Five                      70157452                         NaN
 To and From New York                 70053412        Sorin Dan Mihalcescu

                                                                                   cast  \
 title
 Chocolate                            Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...
 Guatemala: Heart of the Mayan World                                  Christian Morales
 The Zoya Factor                      Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...
 Atlantics                            Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...
 Chip and Potato                      Abigail Oliver, Andrea Libman, Briana Buckmast...
 ...                                                                                ...
 Mad Ron's Prevues from Hell          Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...
 Splatter                             Corey Feldman, Tony Todd, Tara Leigh, Erin Way...
 Just Another Love Story              Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...
 Dinner for Five                                                                    NaN
 To and From New York                 Barbara King, Shaana Diya, John Krisiukenas, Y...

                                                       country  \
 title
 Chocolate                                         South Korea
 Guatemala: Heart of the Mayan World                       NaN
 The Zoya Factor                                         India
 Atlantics                            France, Senegal, Belgium
 Chip and Potato                        Canada, United Kingdom
 ...                                                       ...
 Mad Ron's Prevues from Hell                     United States
 Splatter                                        United States
 Just Another Love Story                               Denmark
 Dinner for Five                                 United States
 To and From New York                            United States

                                             date_added  release_year rating  \
 title
 Chocolate                            November 30, 2019          2019  TV-14
 Guatemala: Heart of the Mayan World  November 30, 2019          2019   TV-G
 The Zoya Factor                      November 30, 2019          2019  TV-14
 Atlantics                            November 29, 2019          2019  TV-14
 Chip and Potato                                    NaN          2019   TV-Y
 ...                                                ...           ...    ...
 Mad Ron's Prevues from Hell           November 1, 2010          1987     NR
 Splatter                             November 18, 2009          2009  TV-14
 Just Another Love Story                    May 5, 2009          2007     NR
 Dinner for Five                       February 4, 2008          2007  TV-MA
 To and From New York                   January 1, 2008          2006     NR

                                       duration  \
 title
 Chocolate                             1 Season
 Guatemala: Heart of the Mayan World     67 min
 The Zoya Factor                        135 min
 Atlantics                              106 min
 Chip and Potato                      2 Seasons
 ...                                        ...
 Mad Ron's Prevues from Hell             84 min
 Splatter                                29 min
 Just Another Love Story                104 min
 Dinner for Five                       1 Season
 To and From New York                    81 min

                                                                              listed_in  \
 title
 Chocolate                            International TV Shows, Korean TV Shows, Roman...
 Guatemala: Heart of the Mayan World                Documentaries, International Movies
 The Zoya Factor                                 Comedies, Dramas, International Movies
 Atlantics                             Dramas, Independent Movies, International Movies
 Chip and Potato                                                               Kids' TV
 ...                                                                                ...
 Mad Ron's Prevues from Hell                                 Cult Movies, Horror Movies
 Splatter                                                                 Horror Movies
 Just Another Love Story                                   Dramas, International Movies
 Dinner for Five                                           Stand-Up Comedy & Talk Shows
 To and From New York                             Dramas, Independent Movies, Thrillers

                                                                            description  \
 title
 Chocolate                            Brought together by meaningful meals in the pa...
 Guatemala: Heart of the Mayan World  From Sierra de las Minas to Esquipulas, explor...
 The Zoya Factor                      A goofy copywriter unwittingly convinces the I...
 Atlantics                            Arranged to marry a rich man, young Ada is cru...
 Chip and Potato                      Lovable pug Chip starts kindergarten, makes ne...
 ...                                                                                ...
 Mad Ron's Prevues from Hell          This collection cherry-picks trailers, forgott...
 Splatter                             After committing suicide, a washed-up rocker r...
 Just Another Love Story              When he causes a car accident that leaves a yo...
 Dinner for Five                      In each episode, four celebrities join host Jo...
 To and From New York                 While covering a story in New York City, a Sea...

                                         type
 title
 Chocolate                            TV Show
 Guatemala: Heart of the Mayan World    Movie
 The Zoya Factor                        Movie
 Atlantics                              Movie
 Chip and Potato                      TV Show
 ...                                      ...
 Mad Ron's Prevues from Hell            Movie
 Splatter                               Movie
 Just Another Love Story                Movie
 Dinner for Five                      TV Show
 To and From New York                   Movie

 [5837 rows x 11 columns],
                                      show_id  director   cast  country  \
 title
 Chocolate                              False      True  False    False
 Guatemala: Heart of the Mayan World    False     False  False     True
 The Zoya Factor                        False     False  False    False
 Atlantics                              False     False  False    False
 Chip and Potato                        False      True  False    False
 ...                                      ...       ...    ...      ...
 Mad Ron's Prevues from Hell            False     False  False    False
 Splatter                               False     False  False    False
 Just Another Love Story                False     False  False    False
 Dinner for Five                        False      True   True    False
 To and From New York                   False     False  False    False

                                      date_added  release_year  rating  \
 title
 Chocolate                                 False         False   False
 Guatemala: Heart of the Mayan World       False         False   False
 The Zoya Factor                           False         False   False
 Atlantics                                 False         False   False
 Chip and Potato                            True         False   False
 ...                                         ...           ...     ...
 Mad Ron's Prevues from Hell               False         False   False
 Splatter                                  False         False   False
 Just Another Love Story                   False         False   False
 Dinner for Five                           False         False   False
 To and From New York                      False         False   False

                                      duration  listed_in  description   type
 title
 Chocolate                               False      False        False  False
 Guatemala: Heart of the Mayan World     False      False        False  False
 The Zoya Factor                         False      False        False  False
 Atlantics                               False      False        False  False
 Chip and Potato                         False      False        False  False
 ...                                       ...        ...          ...    ...
 Mad Ron's Prevues from Hell             False      False        False  False
 Splatter                                False      False        False  False
 Just Another Love Story                 False      False        False  False
 Dinner for Five                         False      False        False  False
 To and From New York                    False      False        False  False

 [5837 rows x 11 columns])

In [39]:
df.describe(include="all")

,show_id,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
count,5.837000e+03,3936,5281,5410,5195,5837.000000,5827,5837,5837,5837,5837
unique,NaN,3108,5087,527,1092,NaN,14,194,449,5829,2
top,NaN,"Raúl Campos, Jan Suter",David Attenborough,United States,"November 1, 2019",NaN,TV-MA,1 Season,Documentaries,A surly septuagenarian gets another chance at ...,Movie
freq,NaN,18,18,1907,94,NaN,1937,1259,297,3,3939
mean,7.730079e+07,NaN,NaN,NaN,NaN,2013.688539,NaN,NaN,NaN,NaN,NaN
std,9.479777e+06,NaN,NaN,NaN,NaN,8.419088,NaN,NaN,NaN,NaN,NaN
min,2.698800e+05,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN,NaN,NaN
25%,8.004520e+07,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN,NaN,NaN
50%,8.016353e+07,NaN,NaN,NaN,NaN,2016.000000,NaN,NaN,NaN,NaN,NaN
75%,8.024188e+07,NaN,NaN,NaN,NaN,2018.000000,NaN,NaN,NaN,NaN,NaN
max,8.122720e+07,NaN,NaN,NaN,NaN,2020.000000,NaN,NaN,NaN,NaN,NaN

In [40]:
df["release_year"].unique()

array([2019, 2018, 2016, 2017, 2001, 2008, 2015, 1980, 1973, 2012, 1987,
       2002, 2013, 1996, 1992, 2007, 2009, 1995, 2014, 1968, 2010, 1999,
       2011, 2000, 1974, 1997, 1993, 2006, 2005, 2003, 2004, 2020, 1998,
       1960, 1958, 1965, 1956, 1978, 1990, 1976, 1962, 1955, 1972, 1991,
       1988, 1986, 1989, 1975, 1985, 1984, 1970, 1994, 1982, 1983, 1967,
       1981, 1979, 1925, 1946, 1977, 1959, 1966, 1971, 1963, 1969, 1945,
       1942, 1944, 1947, 1943, 1954])

In [41]:
df["release_year"].nunique()

71

In [42]:
df["director"].unique()

array([nan, 'Luis Ara, Ignacio Jaunsolo', 'Abhishek Sharma', ...,
       'Jim Monaco', 'Ole Bornedal', 'Sorin Dan Mihalcescu'], dtype=object)

In [44]:
df.shape

(5837, 11)

In [45]:
df

,show_id,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
title,,,,,,,,,,,
Chocolate,81193313,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
Guatemala: Heart of the Mayan World,81197050,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
The Zoya Factor,81213894,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
Atlantics,81082007,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
Chip and Potato,80213643,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show
...,...,...,...,...,...,...,...,...,...,...,...
Mad Ron's Prevues from Hell,70141644,Jim Monaco,"Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...",United States,"November 1, 2010",1987,NR,84 min,"Cult Movies, Horror Movies","This collection cherry-picks trailers, forgott...",Movie
Splatter,70127998,Joe Dante,"Corey Feldman, Tony Todd, Tara Leigh, Erin Way...",United States,"November 18, 2009",2009,TV-14,29 min,Horror Movies,"After committing suicide, a washed-up rocker r...",Movie
Just Another Love Story,70084180,Ole Bornedal,"Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...",Denmark,"May 5, 2009",2007,NR,104 min,"Dramas, International Movies",When he causes a car accident that leaves a yo...,Movie
Dinner for Five,70157452,NaN,NaN,United States,"February 4, 2008",2007,TV-MA,1 Season,Stand-Up Comedy & Talk Shows,"In each episode, four celebrities join host Jo...",TV Show
To and From New York,70053412,Sorin Dan Mihalcescu,"Barbara King, Shaana Diya, John Krisiukenas, Y...",United States,"January 1, 2008",2006,NR,81 min,"Dramas, Independent Movies, Thrillers","While covering a story in New York City, a Sea...",Movie

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5837 entries, Chocolate to To and From New York
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5837 non-null   int64
 1   director      3936 non-null   object
 2   cast          5281 non-null   object
 3   country       5410 non-null   object
 4   date_added    5195 non-null   object
 5   release_year  5837 non-null   int64
 6   rating        5827 non-null   object
 7   duration      5837 non-null   object
 8   listed_in     5837 non-null   object
 9   description   5837 non-null   object
 10  type          5837 non-null   object
dtypes: int64(2), object(9)
memory usage: 676.3+ KB

In [47]:
df.count()

show_id         5837
director        3936
cast            5281
country         5410
date_added      5195
release_year    5837
rating          5827
duration        5837
listed_in       5837
description     5837
type            5837
dtype: int64

In [48]:
df["rating"].value_counts()

rating
TV-MA       1937
TV-14       1593
TV-PG        678
R            439
PG-13        227
NR           218
PG           160
TV-Y7        156
TV-G         147
TV-Y         139
TV-Y7-FV      92
G             32
UR             7
NC-17          2
Name: count, dtype: int64

In [49]:
df["country"].value_counts()

country
United States                                           1907
India                                                    697
United Kingdom                                           336
Japan                                                    168
Canada                                                   139
                                                        ...
Norway, Denmark, Netherlands, Sweden                       1
Ireland, United Kingdom, Greece, France, Netherlands       1
Israel, Germany                                            1
Canada, Germany, France, United States                     1
Spain, Mexico, France                                      1
Name: count, Length: 527, dtype: int64